set username=root
set password=root

sqlldr %username%/%password% "Rodzaj_silnika.ctl"
sqlldr %username%/%password% "Rodzaj_zasilania.ctl"
sqlldr %username%/%password% "Silnik.ctl"
sqlldr %username%/%password% "Kategoria.ctl"
sqlldr %username%/%password% "Uklad_hamulcowy.ctl"
sqlldr %username%/%password% "Rodzaj_skrzyni_biegow.ctl"
sqlldr %username%/%password% "Skrzynia_biegow.ctl"
sqlldr %username%/%password% "Kolor.ctl"
sqlldr %username%/%password% "Typ_nadwozia.ctl"
sqlldr %username%/%password% "Nadwozie.ctl"
sqlldr %username%/%password% "Marka.ctl"
sqlldr %username%/%password% "Model.ctl"
sqlldr %username%/%password% "Samochod.ctl"
sqlldr %username%/%password% "platnosc.ctl"
sqlldr %username%/%password% "pracownik.ctl"
sqlldr %username%/%password% "wojewodztwo.ctl"
sqlldr %username%/%password% "miasto.ctl"
sqlldr %username%/%password% "ulica.ctl"
sqlldr %username%/%password% "klient.ctl"
sqlldr %username%/%password% "wypozyczenie.ctl"
